In [50]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib
import os
os.getcwd()

'C:\\Users\\tkim29'

In [6]:
data = pd.read_excel('Online Retail.xlsx')

In [84]:
data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [85]:
data.isnull().sum() ##Description, CustomerID 결측치 존재

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [86]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
InvoiceNo      541909 non-null object
StockCode      541909 non-null object
Description    540455 non-null object
Quantity       541909 non-null int64
InvoiceDate    541909 non-null datetime64[ns]
UnitPrice      541909 non-null float64
CustomerID     406829 non-null float64
Country        541909 non-null object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

In [87]:
data.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country'],
      dtype='object')

In [88]:
data['InvoiceNo'].unique()

array([536365, 536366, 536367, ..., 581585, 581586, 581587], dtype=object)

In [89]:
data[['StockCode']].head(3)

  StockCode
0    85123A
1     71053
2    84406B

In [123]:
data[data['Description'].isnull()].head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,2010-12-01 11:52:00,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,2010-12-01 14:32:00,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,2010-12-01 14:33:00,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,2010-12-01 14:34:00,0.0,NaN,United Kingdom

In [124]:
data["Description_fillin"] = data["Description"]

In [131]:
data[['Description','Description_fillin']].head()

                           Description                   Description_fillin
0   WHITE HANGING HEART T-LIGHT HOLDER   WHITE HANGING HEART T-LIGHT HOLDER
1                  WHITE METAL LANTERN                  WHITE METAL LANTERN
2       CREAM CUPID HEARTS COAT HANGER       CREAM CUPID HEARTS COAT HANGER
3  KNITTED UNION FLAG HOT WATER BOTTLE  KNITTED UNION FLAG HOT WATER BOTTLE
4       RED WOOLLY HOTTIE WHITE HEART.       RED WOOLLY HOTTIE WHITE HEART.

In [133]:
data.loc[data["Description"].isnull(), "Description_fillin"] = 'No Comments'

In [140]:
data.isnull().sum()

InvoiceNo                  0
StockCode                  0
Description             1454
Quantity                   0
InvoiceDate                0
UnitPrice                  0
CustomerID            135080
Country                    0
Description_fillin         0
dtype: int64

In [145]:
data['Real_Price'] = data['Quantity']*data['UnitPrice']

In [152]:
data['Real_Price'].head()

0    15.30
1    20.34
2    22.00
3    20.34
4    20.34
Name: Real_Price, dtype: float64

In [153]:
data.columns

Index(['InvoiceNo', 'StockCode', 'Description', 'Quantity', 'InvoiceDate',
       'UnitPrice', 'CustomerID', 'Country', 'Description_fillin',
       'CustomerID_fillin', 'Real_Price'],
      dtype='object')

In [141]:
data['CustomerID_fillin'] = data['CustomerID']

In [156]:
data['CustomerID'].head()

0    17850.0
1    17850.0
2    17850.0
3    17850.0
4    17850.0
Name: CustomerID, dtype: float64

In [162]:
data.loc[data["CustomerID"].isnull(), "CustomerID_fillin"] = 99999

In [165]:
data['CustomerID_fillin'].isnull().sum()

0

In [175]:
data.isnull().sum()

InvoiceNo                  0
StockCode                  0
Description             1454
Quantity                   0
InvoiceDate                0
UnitPrice                  0
CustomerID            135080
Country                    0
Description_fillin         0
CustomerID_fillin          0
Real_Price                 0
dtype: int64

In [230]:
data.groupby('CustomerID')

In [231]:
data_gb = data.groupby(by='CustomerID_fillin', axis=0).sum()

In [233]:
data_gb = data_gb.drop('Quantity', axis=1)

In [235]:
data_gb = data_gb.drop('UnitPrice', axis=1)

In [237]:
data_gb = data_gb.drop('CustomerID', axis=1)

In [243]:
data_gb['CustomerID_fillin']==99999

KeyError: 'CustomerID_fillin'

In [203]:
data_country = data.groupby(by='Country').sum()

In [220]:
country_df = data_country[['Real_Price']]

In [222]:
country_df_index=country_df.reset_index()

In [226]:
country_df_index['Real_Price']

0     1.370773e+05
1     1.015432e+04
2     5.484000e+02
3     4.091096e+04
4     1.143600e+03
5     3.666380e+03
6     2.008629e+04
7     1.294629e+04
8     7.077200e+02
9     1.876814e+04
10    2.632768e+05
11    1.291750e+03
12    2.232674e+04
13    1.974039e+05
14    2.216982e+05
15    4.710520e+03
16    1.011704e+04
17    4.310000e+03
18    7.907820e+03
19    1.689051e+04
20    3.534062e+04
21    1.693880e+03
22    1.661060e+03
23    2.505470e+03
24    2.846615e+05
25    3.516346e+04
26    7.213140e+03
27    2.936702e+04
28    1.002310e+03
29    1.311700e+02
30    9.120390e+03
31    5.477458e+04
32    3.659591e+04
33    5.638535e+04
34    1.730920e+03
35    1.902280e+03
36    8.187806e+06
37    4.749790e+03
Name: Real_Price, dtype: float64

In [189]:
data_inv = data.groupby(by='InvoiceNo',)

In [190]:
data_inv.head(3)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,Description_fillin,CustomerID_fillin,Real_Price
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom,WHITE HANGING HEART T-LIGHT HOLDER,17850.0,15.30
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom,WHITE METAL LANTERN,17850.0,20.34
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom,CREAM CUPID HEARTS COAT HANGER,17850.0,22.00
7,536366,22633,HAND WARMER UNION JACK,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,HAND WARMER UNION JACK,17850.0,11.10
8,536366,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 08:28:00,1.85,17850.0,United Kingdom,HAND WARMER RED POLKA DOT,17850.0,11.10
9,536367,84879,ASSORTED COLOUR BIRD ORNAMENT,32,2010-12-01 08:34:00,1.69,13047.0,United Kingdom,ASSORTED COLOUR BIRD ORNAMENT,13047.0,54.08
10,536367,22745,POPPY'S PLAYHOUSE BEDROOM,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom,POPPY'S PLAYHOUSE BEDROOM,13047.0,12.60
11,536367,22748,POPPY'S PLAYHOUSE KITCHEN,6,2010-12-01 08:34:00,2.10,13047.0,United Kingdom,POPPY'S PLAYHOUSE KITCHEN,13047.0,12.60
21,536368,22960,JAM MAKING SET WITH JARS,6,2010-12-01 08:34:00,4.25,13047.0,United Kingdom,JAM MAKING SET WITH JARS,13047.0,25.50
22,536368,22913,RED COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,RED COAT RACK PARIS FASHION,13047.0,14.85
23,536368,22912,YELLOW COAT RACK PARIS FASHION,3,2010-12-01 08:34:00,4.95,13047.0,United Kingdom,YELLOW COAT RACK PARIS FASHION,13047.0,14.85
25,536369,21756,BATH BUILDING BLOCK WORD,3,2010-12-01 08:35:00,5.95,13047.0,United Kingdom,BATH BUILDING BLOCK WORD,13047.0,17.85
26,536370,22728,ALARM CLOCK BAKELIKE PINK,24,2010-12-01 08:45:00,3.75,12583.0,France,ALARM CLOCK BAKELIKE PINK,12583.0,90.00
27,536370,22727,ALARM CLOCK BAKELIKE RED,24,2010-12-01 08:45:00,3.75,12583.0,France,ALARM CLOCK BAKELIKE RED,12583.0,90.00
28,536370,22726,ALARM CLOCK BAKELIKE GREEN,12,2010-12-01 08:45:00,3.75,12583.0,France,ALARM CLOCK BAKELIKE GREEN,12583.0,45.00
46,536371,22086,PAPER CHAIN KIT 50'S CHRISTMAS,80,2010-12-01 09:00:00,2.55,13748.0,United Kingdom,PAPER CHAIN KIT 50'S CHRISTMAS,13748.0,204.00
47,536372,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 09:01:00,1.85,17850.0,United Kingdom,HAND WARMER RED POLKA DOT,17850.0,11.10
48,536372,22633,HAND WARMER UNION JACK,6,2010-12-01 09:01:00,1.85,17850.0,United Kingdom,HAND WARMER UNION JACK,17850.0,11.10
49,536373,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 09:02:00,2.55,17850.0,United Kingdom,WHITE HANGING HEART T-LIGHT HOLDER,17850.0,15.30
50,536373,71053,WHITE METAL LANTERN,6,2010-12-01 09:02:00,3.39,17850.0,United Kingdom,WHITE METAL LANTERN,17850.0,20.34
51,536373,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 09:02:00,2.75,17850.0,United Kingdom,CREAM CUPID HEARTS COAT HANGER,17850.0,22.00
65,536374,21258,VICTORIAN SEWING BOX LARGE,32,2010-12-01 09:09:00,10.95,15100.0,United Kingdom,VICTORIAN SEWING BOX LARGE,15100.0,350.40
66,536375,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 09:32:00,2.55,17850.0,United Kingdom,WHITE HANGING HEART T-LIGHT HOLDER,17850.0,15.30
67,536375,71053,WHITE METAL LANTERN,6,2010-12-01 09:32:00,3.39,17850.0,United Kingdom,WHITE METAL LANTERN,17850.0,20.34
68,536375,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 09:32:00,2.75,17850.0,United Kingdom,CREAM CUPID HEARTS COAT HANGER,17850.0,22.00
82,536376,22114,HOT WATER BOTTLE TEA AND SYMPATHY,48,2010-12-01 09:32:00,3.45,15291.0,United Kingdom,HOT WATER BOTTLE TEA AND SYMPATHY,15291.0,165.60
83,536376,21733,RED HANGING HEART T-LIGHT HOLDER,64,2010-12-01 09:32:00,2.55,15291.0,United Kingdom,RED HANGING HEART T-LIGHT HOLDER,15291.0,163.20
84,536377,22632,HAND WARMER RED POLKA DOT,6,2010-12-01 09:34:00,1.85,17850.0,United Kingdom,HAND WARMER RED POLKA DOT,17850.0,11.10
85,536377,22633,HAND WARMER UNION JACK,6,2010-12-01 09:34:00,1.85,17850.0,United Kingdom,HAND WARMER UNION JACK,17850.0,11.10
86,536378,22386,JUMBO BAG PINK POLKADOT,10,2010-12-01 09:37:00,1.95,14688.0,United Kingdom,JUMBO BAG PINK POLKADOT,14688.0,19.50
...,...,...,...,...,...,...,...,...,...,...,...
541755,581574,22326,ROUND SNACK BOXES SET OF4 WOODLAND,6,2011-12-09 12:09:00,2.95,12526.0,Germany,ROUND SNACK BOXES SET OF4 WOODLAND,12526.0,17.70
541756,581574,22328,ROUND SNACK BOXES SET OF 4 FRUITS,6,2011-12-09 12:09:00,2.95,12526.0,Germany,ROUND SNACK BOXES SET OF 4 FRUITS,12526.0,17.70
541757,581574,23199,JUMBO BAG APPLES,10,2011-12-09 12:09:00,2.08,12526.0,Germany,JUMBO BAG APPLES,12526.0,20.80
541768,581578,POST,POSTAGE,3,2011-12-09 12:16:00,18.00,12713.0,Germany,POSTAGE,12713.0,54.00
541769,581578,21124,SET/10 BLUE POLKADOT PARTY CANDLES,24,2011-12-09 12:16:00,1.25,12713.0,Germany,SET/10 BLUE POLKADOT PARTY CANDLES,12713.0,30.00
541770,581578,21122,SET/10 PINK POLKADOT PARTY CANDLES,24,2011-12-09 12:16:00,1.25,12713.0,Germany,SET/10 PINK POLKADOT PARTY CANDLES,12713.0,30.00
541806,581579,22386,JUMBO BAG PINK POLKADOT,10,2011-12-09 12:19:00,1.79,17581.0,United Kingdom,JUMBO BAG PINK POLKADOT,17581.0,17.90
541807,581579,22411,JUMBO SHOPPER VINTAGE RED PAISLEY,10,2011-12-09 12:19:00,1.79,17581.0,United Kingdom,JUMBO SHOPPER VINTAGE RED PAISLEY,17581.0,17.90
541808,581579,21929,JUMBO BAG PINK VINTAGE PAISLEY,10,2011-12-09 12:19:00,1.79,17581.0,United Kingdom,JUMBO BAG PINK VINTAGE PAISLEY,17581.0,17.90
541836,581580,23334,IVORY WICKER HEART SMALL,4,2011-12-09 12:20:00,0.63,12748.0,United Kingdom,IVORY WICKER HEART SMALL,12748.0,2.52
541837,581580,21790,VINTAGE SNAP CARDS,1,2011-12-09 12:20:00,0.85,12748.0,United Kingdom,VINTAGE SNAP CARDS,12748.0,0.85
541838,581580,84993A,75 GREEN PETIT FOUR CASES,2,2011-12-09 12:20:00,0.42,12748.0,United Kingdom,75 GREEN PETIT FOUR CASES,12748.0,0.84
541860,581581,23562,SET OF 6 RIBBONS PERFECTLY PRETTY,6,2011-12-09 12:20:00,2.89,17581.0,United Kingdom,SET OF 6 RIBBONS PERFECTLY PRETTY,17581.0,17.34
541861,581581,23561,SET OF 6 RIBBONS PARTY,6,2011-12-09 12:20:00,2.89,17581.0,United Kingdom,SET OF 6 RIBBONS PARTY,17581.0,17.34
541862,581581,23681,LUNCH BAG RED VINTAGE DOILY,10,2011-12-09 12:20:00,1.65,17581.0,United Kingdom,LUNCH BAG RED VINTAGE DOILY,17581.0,16.50
541863,581582,23552,BICYCLE PUNCTURE REPAIR KIT,6,2011-12-09 12:21:00,2.08,17581.0,United Kingdom,BICYCLE PUNCTURE REPAIR KIT,17581.0,12.48
541864,581582,23498,CLASSIC BICYCLE CLIPS,12,2011-12-09 12:21:00,1.45,17581.0,United Kingdom,CLASSIC BICYCLE CLIPS,17581.0,17.40
541865,581583,20725,LUNCH BAG RED RETROSPOT,40,2011-12-09 12:23:00,1.45,13777.0,United Kingdom,LUNCH BAG RED RETROSPOT,13777.0,58.00
541866,581583,85038,6 CHOCOLATE LOVE HEART T-LIGHTS,36,2011-12-09 12:23:00,1.85,13777.0,United Kingdom,6 CHOCOLATE LOVE HEART T-LIGHTS,13777.0,66.60
541867,581584,20832,RED FLOCK LOVE HEART PHOTO FRAME,72,2011-12-09 12:25:00,0.72,13777.0,United Kingdom,RED FLOCK LOVE HEART PHOTO FRAME,13777.0,51.84
541868,581584,85038,6 CHOCOLATE LOVE HEART T-LIGHTS,48,2011-12-09 12:25:00,1.85,13777.0,United Kingdom,6 CHOCOLATE LOVE HEART T-LIGHTS,13777.0,88.80
541869,581585,22481,BLACK TEA TOWEL CLASSIC DESIGN,12,2011-12-09 12:31:00,0.39,15804.0,United Kingdom,BLACK TEA TOWEL CLASSIC DESIGN,15804.0,4.68
541870,581585,22915,ASSORTED BOTTLE TOP MAGNETS,24,2011-12-09 12:31:00,0.19,15804.0,United Kingdom,ASSORTED BOTTLE TOP MAGNETS,15804.0,4.56
541871,581585,22178,VICTORIAN GLASS HANGING T-LIGHT,12,2011-12-09 12:31:00,1.95,15804.0,United Kingdom,VICTORIAN GLASS HANGING T-LIGHT,15804.0,23.40
541890,581586,22061,LARGE CAKE STAND HANGING STRAWBERY,8,2011-12-09 12:49:00,2.95,13113.0,United Kingdom,LARGE CAKE STAND HANGING STRAWBERY,13113.0,23.60
541891,581586,23275,SET OF 3 HANGING OWLS OLLIE BEAK,24,2011-12-09 12:49:00,1.25,13113.0,United Kingdom,SET OF 3 HANGING OWLS OLLIE BEAK,13113.0,30.00
541892,581586,21217,RED RETROSPOT ROUND CAKE TINS,24,2011-12-09 12:49:00,8.95,13113.0,United Kingdom,RED RETROSPOT ROUND CAKE TINS,13113.0,214.80
541894,581587,22631,CIRCUS PARADE LUNCH BOX,12,2011-12-09 12:50:00,1.95,12680.0,France,CIRCUS PARADE LUNCH BOX,12680.0,23.40
541895,581587,22556,PLASTERS IN TIN CIRCUS PARADE,12,2011-12-09 12:50:00,1.65,12680.0,France,PLASTERS IN TIN CIRCUS PARADE,12680.0,19.80
541896,581587,22555,PLASTERS IN TIN STRONGMAN,12,2011-12-09 12:50:00,1.65,12680.0,France,PLASTERS IN TIN STRONGMAN,12680.0,19.80